version: 2

project_name: projet-iac-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./main.go
    binary: projet-iac-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Jeomhps/projet-iac-cli/cmd.version={{.Version}}
      - -X github.com/Jeomhps/projet-iac-cli/cmd.commit={{.ShortCommit}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  # Rely on GoReleaser v2 defaults (tar.gz for linux/darwin, zip for windows).
  # This avoids deprecated fields like archives.format_overrides and archives.builds.
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: github
  sort: asc

release:
  draft: false
  prerelease: false
