name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write  # required to create GitHub Releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for GoReleaser changelog and versioning

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # Pin to a specific GoReleaser version; update as needed.
          version: v2.12.7
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
